### ISSUE TITLE
I tried the first testing example, received an error message

### ISSUE THREAD

**Issue by HimmelStein** [okgreece/DescriptiveStats.OBeu#1]
http://okfnrg.math.auth.gr/ocpu/test/ 
method: POST
Endpoint: ../library/DescriptiveStats.OBeu/R/ds.analysis
param name/value
data/sample_df_rudolf
box.out/1.5
corr.methods/"spearman"

received message: HTTP 400 Bad Request
unused argument (box.out = 1.5)
In call:
ds.analysis(data = sample_df_rudolf, box.out = 1.5, corr.method = "spearman")

**Comment by kleanthisk10** [comment]
We are updating one funtion here, soon will be available, correct @larjohn ?

**Comment by kleanthisk10** [comment]
@HimmelStein the functions are updated and ready to use.

**Comment by HimmelStein** [comment]
@kleanthisk10 thanks! tested, and it works. is it also workable for RDF dataset?
